export const COFFEE_LIST = 'COFFEE_LIST';
export const COFFEE_LIST_FULFILLED = 'COFFEE_LIST_FULFILLED';
export const COFFEE_LIST_REJECTED = 'COFFEE_LIST_REJECTED';
export const COFFEE_LIST_PENDING = 'COFFEE_LIST_PENDING';
